insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Ulric', 'Bollans', '1977-04-03', 'M', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Shirlene', 'Sheals', '1971-04-19', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Ernestine', 'Islep', '1974-04-09', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Phil', 'Silby', '1984-05-16', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Nara', 'Larwood', '1976-07-21', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Cristin', 'Rennick', '1991-04-30', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Bastien', 'Arch', '1996-07-11', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Clay', 'Nestor', '1981-01-03', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Annmaria', 'Grimshaw', '1976-08-28', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Alice', 'Marmyon', '1994-04-21', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Freddy', 'Macourek', '1994-01-08', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Umberto', 'Spondley', '1979-10-24', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Aarika', 'Summerell', '1976-09-02', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Tabatha', 'Ongin', '1989-12-26', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Constantino', 'Kingsland', '1985-07-06', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Dewain', 'Coppock', ',1982-02-19', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Tyne', 'Trouel', '1975-03-09', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Charlene', 'Burnet', '1984-09-11', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Bev', 'Bailey', '1870-10-04', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Farley', 'Ferrara', '1871-12-09', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Ellie', 'Salters', '1978-11-15', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Johnnie', 'Maulkin', '1987-02-05', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Vilhelmina', 'Curtiss', '1889-03-07', 'F', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Peyter', 'Pickavance', '1879-08-08', 'M', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Cullen', 'Tredger', '1971-10-10', 'M', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Trixy', 'Mandel', '1980-02-07', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Leela', 'Issit', '1979-03-26', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Harland', 'Grzesiak', '1996-12-07', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Cherry', 'Klimsch', '1988-02-07', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Hillyer', 'Bartczak', '1996-05-30', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('John', 'Leggat', '1991-03-20', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Brigida', 'Drewitt', '1899-02-05', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Malissa', 'Sabbatier', '1872-05-23', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Blinny', 'Tokell', '1978-11-08', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Harriott', 'Kulis', '1981-09-30', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Reynolds', 'Endley', '1986-10-27', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Lyndsay', 'Clearley', '1987-04-04', 'F', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Reggis', 'Peperell', '1875-06-02', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Nat', 'Ramm', '1889-06-25', 'M', 'Sydney');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Adelaida', 'McHarry', '1890-05-07', 'F', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Angie', 'Darrington', '1970-06-21', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Anneliese', 'Kolodziej', '1975-01-29', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Benedicto', 'Ettles', '1996-01-17', 'M', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Fifi', 'Prigmore', '1892-08-20', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Sile', 'Madoc Jones', '1894-07-14', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Alfy', 'Fairbrother', '1996-01-07', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Arluene', 'Gerhardt', '1981-09-18', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Benjie', 'MacCrachen', '1983-10-30', 'M', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Giusto', 'Cromwell', '1972-07-07', 'M', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Sander', 'Husselbee', '1980-04-23', 'M', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Meris', 'Nottingam', '1973-07-04', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Hallie', 'Flisher', '1988-05-01', 'F', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Rheba', 'Jorat', '1984-09-26', 'F', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Karlens', 'Riggulsford', '1994-06-17', 'M', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Clem', 'Farrand', '1996-01-24', 'F', 'tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Bianka', 'Walkinshaw', '1993-11-24', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Ertha', 'Cooke', '1974-05-01', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Natassia', 'Parlett', '1975-11-26', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Frankie', 'McCullock', '1970-05-10', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Anakin', 'Skywalker', '1955-05-04', 'M', 'Tatooine');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Thurstan', 'Mordue', '1994-03-17', 'M', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Carling', 'Harbach', '1970-01-20', 'M', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Arlena', 'Lakenton', '1986-03-11', 'F', 'Tokyo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Abbie', 'Surmeir', '1982-01-03', 'F', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Jennie', 'Pirri', '1989-01-28', 'F', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Thurston', 'Stranahan', '1972-09-04', 'M', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Hedwig', 'Tythe', '1974-01-15', 'F', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Nicholle', 'Muirhead', '1994-07-23', 'F', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Luke', 'Sievewright', '1994-11-26', 'M', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Ambros', 'Colquite', '1991-07-08', 'M', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Der', 'Jarrette', '1978-03-06', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Kaitlynn', 'Corneck', '1981-05-09', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Boigie', 'Sottell', '1999-09-07', 'M', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Nathalia', 'Geneay', '1990-12-05', 'F', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Patrizio', 'Cleft', '1974-03-17', 'M', 'Osaka');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Wandie', 'Roblett', '1982-08-27', 'F', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Charles', 'Mager', '1983-11-06', 'M', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Napoleon', 'Renak', '1970-12-16', 'M', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Marnie', 'McCurlye', '1986-08-03', 'F', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Bertie', 'Guidi', '1994-08-08', 'M', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Anderea', 'Lowdyane', '1970-02-22', 'F', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Pooh', 'Wimpenny', '1981-05-02', 'F', 'Abuja');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Mamie', 'Gisburne', '1999-05-29', 'F', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Jervis', 'Ruhben', '1973-02-13', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Abbye', 'Dadge', '1987-03-20', 'F', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Saunderson', 'Bolle', '1977-06-21', 'M', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Hastings', 'MacPake', '1981-08-04', 'M', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Branden', 'Leftridge', '1971-07-09', 'M', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Gerrie', 'Concannon', '1986-08-30', 'F', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Morie', 'Pregel', '1998-05-06', 'M', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Pebrook', 'Townley', '1997-01-22', 'M', 'Nairobi');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Filippo', 'Sherville', '1983-01-11', 'M', 'Sapporo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Pepita', 'Farloe', '1970-02-01', 'F', 'Sapporo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Berti', 'Zorer', '1972-08-19', 'M', 'Sapporo');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Putnam', 'Eliasen', '1980-01-31', 'M', 'Kyoto');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Nils', 'Groomebridge', '1990-07-21', 'M', 'Yokohama');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Gardy', 'Fairlie', '1999-05-08', 'M', 'Yokohama');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Lewiss', 'Adlem', '1988-06-15', 'M', 'Nagoya');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Rhett', 'Orman', '1975-08-14', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Foster', 'Langlais', '1977-07-11', 'M', 'San Francisco');
insert into students (first_name, last_name, date_of_birth, gender, town_of_origin) values ('Merell', 'Browell', '1981-02-17', 'M', 'San Francisco');
